str1="albin"
str2="joseph"
str3="helloworld"
print(str1[4])
print(str3[5])
print(str1+str2)
print(3*str1[4])
print(2*str1)
print(str1[4])
print(str1[1:4])
print(str3[0:7:2])
print(str1[::])
print(str3[-8:-4])
print(str1[::-1])

print(len(str1))
print(str1.title())
print(str1.capitalize())
print(str1.isupper())
print(str1.upper())
print(str3.count("l"))
print(str3.count("l",5,9))
print(str3.find("l"))
